
package vista;
import poo.Multa;
import conexion.ConectarBD;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author capri
 */
public class AgenteTransito extends javax.swing.JFrame {
    ArrayList<Multa> listaMultas = new ArrayList<>();
    Multa ingresaMulta;
    ConectarBD con = new ConectarBD();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd"); 
     Date fechaActual = new Date();
     String fechaTexto = formatoFecha.format(fechaActual); 
     // Establecer la fecha en el JTextField 
      int fila;


   private int idUsuario;

    
    public AgenteTransito(int idUsuario) {
        this.idUsuario = idUsuario; // Guardar el ID del usuario
        initComponents();
        //mostrarMensajeConId();
        setLocationRelativeTo(null);
        txtFecha.setText(fechaTexto);
        txtFecha.setEditable(false);
        consultaDatos();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblIngresarPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        btnAyuda = new javax.swing.JButton();
        btnAgregarMulta = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtMultas = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 5, 52));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Registro de Multas ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo para agregar multas de tráfico (1).png"))); // NOI18N

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Ingresa La fecha");

        lblIngresarPlaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIngresarPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresarPlaca.setText("Agregar Placa Vehicular");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Agrega descripcion");

        lblMonto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setText("Agregar Monto");

        btnAyuda.setBackground(new java.awt.Color(102, 255, 102));
        btnAyuda.setForeground(new java.awt.Color(0, 0, 0));
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnAgregarMulta.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregarMulta.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarMulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnAgregarMulta.setText("Agregar Multa ");
        btnAgregarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMultaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(102, 255, 102));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnSalir.setText("Salir ");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        JtMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Placa", "Descripcion", "Monto"
            }
        ));
        JtMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtMultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JtMultas);

        btnModificar.setBackground(new java.awt.Color(102, 255, 102));
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(102, 255, 102));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFecha)
                            .addComponent(lblIngresarPlaca)
                            .addComponent(lblDescripcion)
                            .addComponent(lblMonto)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtPlaca)
                            .addComponent(txtDescripcion)
                            .addComponent(txtMontoTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnAgregarMulta)
                        .addGap(35, 35, 35)
                        .addComponent(btnModificar)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(36, 36, 36)
                        .addComponent(lblFecha)
                        .addGap(29, 29, 29)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lblIngresarPlaca)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnAyuda)))
                        .addGap(34, 34, 34)
                        .addComponent(lblDescripcion)
                        .addGap(35, 35, 35)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblMonto)
                        .addGap(34, 34, 34)
                        .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMulta)
                    .addComponent(btnSalir)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMultaActionPerformed
       String placa = txtPlaca.getText();
       String descripcion = txtDescripcion.getText();
       int monto = Integer.parseInt(txtMontoTotal.getText());
       int idVehiculo;
       int idAgente = idUsuario;
        if (placa.isEmpty() || descripcion.isEmpty() || monto == 0) {
              JOptionPane.showMessageDialog(null, "No Puedes Dejar Campos Vacios");
        } else {
             String buscaPlaca = "SELECT id_vehiculo FROM Vehiculo WHERE PLACA = '"+placa+"' ";
            
            try {
                con.conectarBDOracle();
                con.rs =con.stmt.executeQuery(buscaPlaca);
                JOptionPane.showInternalMessageDialog(null, "Buscando Placa  Espere .....");
                if (con.rs.next()== true) {
                    idVehiculo = con.rs.getInt("id_vehiculo");
                    // Inserción de la multa
            String insertaMulta = "INSERT INTO MULTA (ID_Multa, Fecha, Motivo, Monto_Total, id_Agente, ID_Vehiculo) " +
                                  "VALUES (seq_multa.NEXTVAL, SYSDATE, ?, ?, ?, ?)";

            try (PreparedStatement stmt = con.cn.prepareStatement(insertaMulta)) {
                stmt.setString(1, descripcion); // Motivo de la multa
                stmt.setInt(2, monto); // Monto total de la multa
                stmt.setInt(3, idAgente); // ID del agente
                stmt.setInt(4, idVehiculo); // ID del vehículo

                int rowsAffected = stmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Multa registrada correctamente");
                    limpiarCasillas();
                    consultaDatos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar la multa");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al insertar la multa\n" + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No Existe La Placa Con Esos Datos");
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error 4 de BD Busqueda\n" + ex.getMessage());
           }
        }
    }//GEN-LAST:event_btnAgregarMultaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        PanelPrincipal pane = new PanelPrincipal();
        pane.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        JOptionPane.showMessageDialog(null, "Si no aparece la placa\n Significa que Es Falsa la Paca");
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void JtMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtMultasMouseClicked
        int selecion = JtMultas.getSelectedRow();
        this.txtPlaca.setText(JtMultas.getValueAt(selecion,1).toString());
        this.txtDescripcion.setText(JtMultas.getValueAt(selecion,2).toString());
        this.txtMontoTotal.setText(JtMultas.getValueAt(selecion,3).toString());
        fila = selecion;
        
    }//GEN-LAST:event_JtMultasMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = JtMultas.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una multa para eliminar.");
            return;
        } else {
            try {
                // Obtener el ID de la multa de la tabla
                String placa = JtMultas.getValueAt(filaSeleccionada, 1).toString();
                String buscarMulta = "SELECT ID_Multa FROM MULTA m JOIN Vehiculo v ON m.ID_Vehiculo = v.id_vehiculo WHERE v.PLACA = '" + placa + "'";
                
                con.conectarBDOracle();
                con.rs = con.stmt.executeQuery(buscarMulta);
                
                if (con.rs.next()) {
                    int idMulta = con.rs.getInt("ID_Multa");
                    
                    // Eliminar la multa de la base de datos
                    String eliminarMulta = "DELETE FROM MULTA WHERE ID_Multa = ?";
                    try (PreparedStatement stmt = con.cn.prepareStatement(eliminarMulta)) {
                        stmt.setInt(1, idMulta);
                        
                        int rowsAffected = stmt.executeUpdate();
                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(null, "Multa eliminada correctamente");
                            limpiarCasillas();
                            consultaDatos();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al eliminar la multa");
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error al eliminar la multa\n" + ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró la multa con esa placa");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la búsqueda de la multa\n" + ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       int filaSeleccionada = JtMultas.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una multa para modificar.");
            return;
        } else {
            try {
                // Obtener el ID de la multa de la tabla
                String placa = JtMultas.getValueAt(filaSeleccionada, 1).toString();
                String buscarMulta = "SELECT ID_Multa FROM MULTA m JOIN Vehiculo v ON m.ID_Vehiculo = v.id_vehiculo WHERE v.PLACA = '" + placa + "'";
                
                con.conectarBDOracle();
                con.rs = con.stmt.executeQuery(buscarMulta);
                
                if (con.rs.next()) {
                    int idMulta = con.rs.getInt("ID_Multa");
                    String descripcion = txtDescripcion.getText();
                    int monto = Integer.parseInt(txtMontoTotal.getText());
                    
                    // Modificar la multa en la base de datos
                    String modificarMulta = "UPDATE MULTA SET Motivo = ?, Monto_Total = ? WHERE ID_Multa = ?";
                    try (PreparedStatement stmt = con.cn.prepareStatement(modificarMulta)) {
                        stmt.setString(1, descripcion);
                        stmt.setInt(2, monto);
                        stmt.setInt(3, idMulta);
                        
                        int rowsAffected = stmt.executeUpdate();
                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(null, "Multa modificada correctamente");
                            limpiarCasillas();
                            consultaDatos();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al modificar la multa");
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error al modificar la multa\n" + ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró la multa con esa placa");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la búsqueda de la multa\n" + ex.getMessage());
            }
        }

       
                
    }//GEN-LAST:event_btnModificarActionPerformed
 private void consultaDatos(){
try {
         con.conectarBDOracle();
            DefaultTableModel modeloMulta = new DefaultTableModel();
            this.JtMultas.setModel(modeloMulta);
            con.rs = con.stmt.executeQuery("SELECT m.fecha,v.PLACA, m.Motivo, m.Monto_Total FROM MULTA m JOIN Vehiculo v ON m.ID_Vehiculo = v.id_vehiculo");
            ResultSetMetaData rsmd = con.rs.getMetaData();
            int cantidadColumnas = rsmd.getColumnCount();
            modeloMulta.addColumn("FECHA");
            modeloMulta.addColumn("PLACA");
            modeloMulta.addColumn("Motivo");
            modeloMulta.addColumn("Monto");
            while(con.rs.next()){
                  Object []fila = new Object[cantidadColumnas];
                  for (int i = 0; i < cantidadColumnas; i++) {//Inicia For
                      fila[i] = con.rs.getObject(i+1);
                  }//Termina for
                  
                  modeloMulta.addRow(fila);
              }
            
            
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Error 2. de BD Consulta\n"+ex);
        }

       
   }
    public void limpiarCasillas(){
        this.txtPlaca.setText(null);
        this.txtDescripcion.setText(null);
        this.txtMontoTotal.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgenteTransito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgenteTransito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgenteTransito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgenteTransito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgenteTransito(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtMultas;
    private javax.swing.JButton btnAgregarMulta;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIngresarPlaca;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
