
package vista;

import javax.swing.JOptionPane;
import poo.Vehiculo;
import poo.Conductor;
import conexion.ConectarBD;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author capri
 */
public class ModificarVehiuculo extends javax.swing.JFrame {
    ConectarBD con = new ConectarBD();

    
    public ModificarVehiuculo() {
        initComponents();
        setLocationRelativeTo(null);
        txtIDVehiculo.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMatriculaBusqueda = new javax.swing.JLabel();
        txtMatriculaBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        paneDatosVehiculo = new javax.swing.JPanel();
        lblMatricula = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblAniio = new javax.swing.JLabel();
        idConductor = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtIDVehiculo = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnModificarRegistro = new javax.swing.JButton();
        btnEliminarRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatosVehiculo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 5, 52));

        jPanel2.setBackground(new java.awt.Color(1, 5, 52));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Modificar El Registro ");

        lblMatriculaBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMatriculaBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        lblMatriculaBusqueda.setText("Ingresa La Maticula Del Vehiuclo");

        txtMatriculaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaBusquedaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        paneDatosVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        paneDatosVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Vehiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        lblMatricula.setForeground(new java.awt.Color(0, 0, 0));
        lblMatricula.setText("Placa");

        lblMarca.setForeground(new java.awt.Color(0, 0, 0));
        lblMarca.setText("Marca");

        lblModelo.setForeground(new java.awt.Color(0, 0, 0));
        lblModelo.setText("Modelo");

        lblAniio.setForeground(new java.awt.Color(0, 0, 0));
        lblAniio.setText("Año");

        idConductor.setForeground(new java.awt.Color(0, 0, 0));
        idConductor.setText("ID Vehiculo");

        javax.swing.GroupLayout paneDatosVehiculoLayout = new javax.swing.GroupLayout(paneDatosVehiculo);
        paneDatosVehiculo.setLayout(paneDatosVehiculoLayout);
        paneDatosVehiculoLayout.setHorizontalGroup(
            paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDatosVehiculoLayout.createSequentialGroup()
                .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneDatosVehiculoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarca)
                            .addComponent(lblModelo)
                            .addComponent(lblMatricula)))
                    .addGroup(paneDatosVehiculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idConductor)
                            .addComponent(lblAniio))))
                .addGap(26, 26, 26)
                .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMarca)
                    .addGroup(paneDatosVehiculoLayout.createSequentialGroup()
                        .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtModelo)
                            .addComponent(txtAnio)
                            .addComponent(txtIDVehiculo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(112, 112, 112))
        );
        paneDatosVehiculoLayout.setVerticalGroup(
            paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDatosVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAniio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idConductor)
                    .addComponent(txtIDVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/una patrulla modificado con un tamaño de pixeles de 100 por 100 (1).png"))); // NOI18N

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnModificarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnModificarRegistro.setText("Modificar");
        btnModificarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRegistroActionPerformed(evt);
            }
        });

        btnEliminarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnEliminarRegistro.setText("Eliminar");
        btnEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRegistroActionPerformed(evt);
            }
        });

        jtDatosVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Anio", "Id_Vehiculo"
            }
        ));
        jScrollPane1.setViewportView(jtDatosVehiculo);

        jButton1.setText("Consultar Datos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMatriculaBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMatriculaBusqueda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paneDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarRegistro)
                            .addComponent(btnEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(16, 16, 16))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(27, 27, 27)
                        .addComponent(lblMatriculaBusqueda)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatriculaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(26, 26, 26)
                        .addComponent(paneDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnModificarRegistro)
                                .addGap(44, 44, 44)
                                .addComponent(btnEliminarRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVolver)
                            .addComponent(jButton1))
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaBusquedaActionPerformed

    }//GEN-LAST:event_txtMatriculaBusquedaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String matriculaIngresada = txtMatriculaBusqueda.getText();
        if (matriculaIngresada.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes Ingresar La Matricula Para Realizar La Busqueda");
        } else {
            try {
                con.conectarBDOracle();
                String busqueda = "SELECT placa,marca,modelo,anio,id_vehiculo FROM vehiculo WHERE placa = '"+matriculaIngresada+"' ";
                con.rs = con.stmt.executeQuery(busqueda);
                JOptionPane.showInternalMessageDialog(null, "Buscando Vehiculo Espere .....");
                if (con.rs.next() == true) {
                    this.txtMatricula.setText(con.rs.getString("placa"));
                    this.txtMarca.setText(con.rs.getNString("marca"));
                    this.txtModelo.setText(con.rs.getString("modelo"));
                    this.txtAnio.setText(con.rs.getNString("anio"));
                    this.txtIDVehiculo.setText(con.rs.getString("id_vehiculo"));
                    JOptionPane.showInternalMessageDialog(null, "Vehiculo Encontrado Con Exito\nPuedes Modificar Los datos\nTambien Lo Puedes Eliminar");
                } else {
                    JOptionPane.showMessageDialog(null, "No Existe La Placa Con Esos Datos");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error 4 de BD Busqueda\n" +ex);
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Administrador admin = new Administrador();
        admin.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnModificarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRegistroActionPerformed
         String placa = txtMatricula.getText();
         String marca = txtMarca.getText();
         String modelo = txtModelo.getText();
         String anioTexto = txtAnio.getText();
         String idTexto = txtIDVehiculo.getText();
         if (placa.isEmpty() || marca.isEmpty() || modelo.isEmpty() || anioTexto.isEmpty() || idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes Realizar Primero La Busqueda Para Editar Los Datos");
        } else {
             int anio = Integer.parseInt(anioTexto);
             int idVehiuclo = Integer.parseInt(idTexto);
             try {
                 con.conectarBDOracle();
                 String editarSQL= " UPDATE vehiculo SET placa = ' "+placa+ " ' ,marca = ' "+marca+ " ', modelo ='"+modelo+" ',anio = ' "+anio+"' WHERE id_vehiculo = '"+idVehiuclo+"'  ";
                 con.stmt.executeUpdate(editarSQL);
                 JOptionPane.showMessageDialog(null,"Vehiculo Editado Con Exito\n Verifica La Consulta ");
                 limpiarCasillas();
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Error Al Editar El Vehiculo"+ex);
             }
        }
        
    }//GEN-LAST:event_btnModificarRegistroActionPerformed

    private void btnEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRegistroActionPerformed
        String idTexto = txtIDVehiculo.getText();
        int confirmarBaja;
         if (idTexto.isEmpty()) {
             JOptionPane.showMessageDialog(null, "Debes Hacer La Busqueda Del Vehiculo Para Poder Eliminarlo");
        } else {
             int idVehiculo = Integer.parseInt(idTexto);
             try {
                 con.conectarBDOracle();
                 confirmarBaja = con.stmt.executeUpdate("DELETE FROM vehiculo WHERE id_vehiculo = '"+idVehiculo+"' ");
                 if (confirmarBaja == 1) {
                       JOptionPane.showMessageDialog(null, "Se Elimino Conductor De La Base De Datos \n"+confirmarBaja);
                     limpiarCasillas();
                     
                 } else {
                     JOptionPane.showMessageDialog(null, "No se Encontro El Id del Vehiculo");
                 }
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Error Al Eliminar El Vehiculo De La Base De Datos"+ex);
             }
        }
    }//GEN-LAST:event_btnEliminarRegistroActionPerformed
    public void limpiarCasillas(){
        this.txtMatriculaBusqueda.setText(null);
        this.txtMatricula.setText(null);
        this.txtMarca.setText(null);
        this.txtModelo.setText(null);
        this.txtAnio.setText(null);
        this.txtIDVehiculo.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarVehiuculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarVehiuculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarVehiuculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarVehiuculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarVehiuculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarRegistro;
    private javax.swing.JButton btnModificarRegistro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel idConductor;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtDatosVehiculo;
    private javax.swing.JLabel lblAniio;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMatriculaBusqueda;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel paneDatosVehiculo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtIDVehiculo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatriculaBusqueda;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
