package vista;
import poo.PagoMulta;
import conexion.ConectarBD;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author capri
 */
public class PagarMulta extends javax.swing.JFrame {
    ConectarBD con = new ConectarBD();
    int fila;
    public PagarMulta() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Pago De Multa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPlacaBuscar = new javax.swing.JTextField();
        btnBuscarPlaca = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMultasTable = new javax.swing.JTable();
        btnPagar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 5, 52));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de Multas de transito");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trans.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa Placa");

        txtPlacaBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacaBuscar.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscarPlaca.setBackground(new java.awt.Color(102, 255, 102));
        btnBuscarPlaca.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnBuscarPlaca.setText("Buscar Placa ");
        btnBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlacaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista De Multas Del Reglamento De Trandito");

        jtMultasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", " Motivo", "Costo"
            }
        ));
        jtMultasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMultasTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtMultasTable);

        btnPagar.setBackground(new java.awt.Color(102, 255, 102));
        btnPagar.setForeground(new java.awt.Color(0, 0, 0));
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(102, 255, 102));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(txtPlacaBuscar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnBuscarPlaca)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlacaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPagar)
                        .addComponent(btnSalir))
                    .addComponent(btnBuscarPlaca))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlacaActionPerformed
          String placa = txtPlacaBuscar.getText();
    if (placa.isEmpty()) {
        JOptionPane.showMessageDialog(null, "No Puede Haber Campos Vacios");
    } else {
        String busquedaSQL = "SELECT v.PLACA, m.Motivo, m.Monto_Total FROM MULTA m JOIN Vehiculo v ON v.id_vehiculo = m.ID_Vehiculo WHERE v.PLACA = '" + placa + "'";
        try {
            con.conectarBDOracle();
            JOptionPane.showInternalMessageDialog(null, "Buscando Placa, Espere...");

            con.rs = con.stmt.executeQuery(busquedaSQL);
            if (con.rs.next()) {
                DefaultTableModel modeloMulta = new DefaultTableModel();
                this.jtMultasTable.setModel(modeloMulta);
                ResultSetMetaData rsmd = con.rs.getMetaData();
                int cantidadColumnas = rsmd.getColumnCount();
                modeloMulta.addColumn("PLACA");
                modeloMulta.addColumn("Motivo");
                modeloMulta.addColumn("Monto");
                
                do {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i] = con.rs.getObject(i + 1);
                    }
                    modeloMulta.addRow(fila);
                } while (con.rs.next());

                JOptionPane.showMessageDialog(null, "Búsqueda completada.");

            } else {
                JOptionPane.showMessageDialog(null, "La Placa Ingresada no tiene Multas");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la búsqueda de multas\n" + ex.getMessage());
          }
        }
    }//GEN-LAST:event_btnBuscarPlacaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jtMultasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMultasTableMouseClicked
        int selecion = jtMultasTable.getSelectedRow();
        fila = selecion;
    }//GEN-LAST:event_jtMultasTableMouseClicked

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
         int filaSeleccionada = jtMultasTable.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione La Multa A  Pagar.");
            return;
        }
        else{
           String valorSeleccionado = jtMultasTable.getValueAt(filaSeleccionada, 0).toString(); 
           // Guardar el valor en una variable String valorGuardado = valorSeleccionado;
           String valorGuardado = valorSeleccionado;
          // String buscarMulta = "SELECT ID_Multa FROM MULTA m JOIN Vehiculo v ON m.ID_Vehiculo = v.id_vehiculo WHERE v.PLACA = '" +valorGuardado+ "'";
            String buscarMulta = "SELECT m.ID_Multa, m.Fecha, m.Motivo, m.Monto_Total FROM MULTA m JOIN Vehiculo v ON m.ID_Vehiculo = v.id_vehiculo  WHERE v.PLACA ='"+valorGuardado+"'";
           
           try{
                con.conectarBDOracle();
                con.rs = con.stmt.executeQuery(buscarMulta);
                
                if (con.rs.next()) {
                    int idMulta = con.rs.getInt("ID_Multa");
                    String fecha = con.rs.getString("Fecha");
                    String motivo = con.rs.getString("Motivo");
                    int monto = con.rs.getInt("Monto_Total");
                   
                    
                    // Eliminar la multa de la base de datos
                    String eliminarMulta = "DELETE FROM MULTA WHERE ID_Multa = ?";
                    try (PreparedStatement stmt = con.cn.prepareStatement(eliminarMulta)) {
                        stmt.setInt(1, idMulta);
                        int rowsAffected = stmt.executeUpdate();
                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(null, "Multa Pagada correctamente");
                            //limpiarCasillas();
                            
                            // Generar ticket de multa pagada en PDF
                           // generarTicketPDF(fecha, valorGuardado, motivo, monto);
                             imprimirTicket(fecha, valorGuardado, motivo, monto);
                           
                            consultarDatos();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al eliminar la multa");
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error al eliminar la multa\n" + ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró la multa con esa placa");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la búsqueda de la multa\n" + ex.getMessage());
            }
        
           
            
        } 
    }//GEN-LAST:event_btnPagarActionPerformed
     private void imprimirTicket(String fecha, String placa, String motivo, int monto) {
    String ticket = "********** Ticket de Multa Pagada **********\n" +
                    "Fecha: " + fecha + "\n" +
                    "Placa: " + placa + "\n" +
                    "Motivo: " + motivo + "\n" +
                    "Monto: $" + monto + "\n" +
                    "*******************************************";
    JOptionPane.showMessageDialog(null, ticket, "Ticket de Multa Pagada", JOptionPane.INFORMATION_MESSAGE);
}

   /* private void generarTicketPDF(String fecha, String placa, String motivo, int monto) {
        try {
            String ruta = "ticket_multa_pagada_" + placa + ".pdf";
            PdfWriter writer = new PdfWriter(ruta);
            com.itextpdf.kernel.pdf.PdfDocument pdf = new com.itextpdf.kernel.pdf.PdfDocument(writer);
            Document documento = new Document(pdf);

            documento.add(new Paragraph("********** Ticket de Multa Pagada **********"));
            documento.add(new Paragraph("Fecha: " + fecha));
            documento.add(new Paragraph("Placa: " + placa));
            documento.add(new Paragraph("Motivo: " + motivo));
            documento.add(new Paragraph("Monto: $" + monto));
            documento.add(new Paragraph("*******************************************"));

            documento.close();
            JOptionPane.showMessageDialog(null, "Ticket guardado en: " + ruta, "Ticket de Multa Pagada", JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar el ticket\n" + ex.getMessage());
        }
    }*/

public void consultarDatos(){
try{
           String matricula = txtPlacaBuscar.getText();
          String busquedaSQL = "SELECT v.PLACA, m.Motivo, m.Monto_Total FROM MULTA m JOIN Vehiculo v ON v.id_vehiculo = m.ID_Vehiculo WHERE v.PLACA = '" +matricula + "'";
           DefaultTableModel modeloMulta = new DefaultTableModel();
            this.jtMultasTable.setModel(modeloMulta);
            con.rs = con.stmt.executeQuery(busquedaSQL);
            ResultSetMetaData rsmd = con.rs.getMetaData();
            int cantidadColumnas = rsmd.getColumnCount();
            modeloMulta.addColumn("PLACA");
            modeloMulta.addColumn("Motivo");
            modeloMulta.addColumn("Monto");
            while(con.rs.next()){
                  Object []fila = new Object[cantidadColumnas];
                  for (int i = 0; i < cantidadColumnas; i++) {//Inicia For
                      fila[i] = con.rs.getObject(i+1);
                  }//Termina for
                  
                  modeloMulta.addRow(fila);
              }
            
            
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Error 2. de BD Consulta\n"+ex);
        }
      

  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarMulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPlaca;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtMultasTable;
    private javax.swing.JTextField txtPlacaBuscar;
    // End of variables declaration//GEN-END:variables
}
