
package vista;
import poo.Conductor;
import conexion.ConectarBD;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author capri
 */
public class RegistroConductor extends javax.swing.JFrame {
    ArrayList<Conductor> listaConductores = new ArrayList<>();
    Conductor ingresaConductor;
    ConectarBD con = new ConectarBD();
    public RegistroConductor() {
        initComponents();
         setLocationRelativeTo(null);//Centra la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        paneRegistroConductor = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNumeroLicencia = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnRegistarConductor = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        txtNumeroLicencia = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneRegistroConductor.setBackground(new java.awt.Color(1, 5, 52));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Registro De Conductores");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo de 64 por 64 px de registro de conductores (1).png"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        lblNumeroLicencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumeroLicencia.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroLicencia.setText("No_Licencia");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Telefono");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnRegistarConductor.setBackground(new java.awt.Color(51, 255, 51));
        btnRegistarConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistarConductor.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistarConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/github.png"))); // NOI18N
        btnRegistarConductor.setText("Registar Conductor");
        btnRegistarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarConductorActionPerformed(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo");

        btnVolver.setText("Volver ");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtNumeroLicencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout paneRegistroConductorLayout = new javax.swing.GroupLayout(paneRegistroConductor);
        paneRegistroConductor.setLayout(paneRegistroConductorLayout);
        paneRegistroConductorLayout.setHorizontalGroup(
            paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegistroConductorLayout.createSequentialGroup()
                .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneRegistroConductorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3))
                    .addGroup(paneRegistroConductorLayout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegistroConductorLayout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(412, 412, 412))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegistroConductorLayout.createSequentialGroup()
                                .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(paneRegistroConductorLayout.createSequentialGroup()
                                        .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(paneRegistroConductorLayout.createSequentialGroup()
                                                .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblNumeroLicencia)
                                                    .addComponent(lblNombre))
                                                .addGap(47, 47, 47))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneRegistroConductorLayout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblCorreo)
                                                    .addComponent(lblTelefono))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(183, 183, 183)))))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegistroConductorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistarConductor)
                .addGap(37, 37, 37))
        );
        paneRegistroConductorLayout.setVerticalGroup(
            paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRegistroConductorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistarConductor)
                    .addComponent(btnVolver))
                .addGap(47, 47, 47))
            .addGroup(paneRegistroConductorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitulo)
                .addGap(34, 34, 34)
                .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumeroLicencia)
                    .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegistroConductorLayout.createSequentialGroup()
                        .addGroup(paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegistroConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCorreo)))
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneRegistroConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneRegistroConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarConductorActionPerformed
       String nom = txtNombre.getText();
       String noLic= txtNumeroLicencia.getText();
       long cel = Long.parseLong(txtTelefono.getText());
       String correo = txtCorreo.getText();
       
        if (nom.isEmpty() || noLic.isEmpty()  ||correo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No puedes Dejar espacios Vacios");
        } else {
            ingresaConductor = new Conductor(WIDTH, nom, noLic, cel, correo);
            listaConductores.add(ingresaConductor);
            JOptionPane.showMessageDialog(null, "Se Ha ingresado Correctamente El Conductor");
            
            try {
                con.conectarBDOracle();
                String altaConductor = "INSERT INTO CONDUCTOR (ID_Conductor, Nombre, No_Licencia, Telefono, Correo) " +
                     "VALUES (seq_id_conductor.NEXTVAL, '" + ingresaConductor.getNombre() + "', '" + 
                     ingresaConductor.getNumLicencia() + "', '" + ingresaConductor.getCelular() + "', '" + 
                     ingresaConductor.getCorreo()+ "')";
                     con.stmt.executeUpdate(altaConductor);
                     limpiarCasillas();
                     JOptionPane.showMessageDialog(null, "Registro insertado con exito");   
            } catch ( SQLException ex) {
                 JOptionPane.showMessageDialog(null, "No se Pudo Registrar El Conductor a la Base de datos"+ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnRegistarConductorActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Administrador admin = new  Administrador();
        admin.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnVolverActionPerformed
   public void limpiarCasillas(){
        this.txtNombre.setText("");
        this.txtNumeroLicencia.setText("");
        this.txtTelefono.setText("");
        this.txtCorreo.setText("");
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistarConductor;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroLicencia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel paneRegistroConductor;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroLicencia;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
